1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'. 
Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().


In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd

import re
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
import os

from sklearn.feature_extraction.text import CountVectorizer


In [17]:
df = pd.read_pickle('/content/drive/MyDrive/Geekbrainst/combine_df.pkl')
df.head()

id  ...                                   tweet_lemmatized
0   1  ...  [father, dysfunctional, selfish, drag, kid, dy...
1   2  ...  [thank, lyft, credit, use, cause, offer, wheel...
2   3  ...                                  [bihday, majesty]
3   4  ...                      [model, love, take, time, ur]
4   5  ...                  [factsguide, society, motivation]

[5 rows x 7 columns]

In [18]:
df.columns

Index(['id', 'label', 'tweet', 'tweet_token', 'tweet_token_filtered',
       'tweet_stemmed', 'tweet_lemmatized'],
      dtype='object')

In [19]:
from nltk.corpus import stopwords #импортируем стоп слова
nltk.download('stopwords')
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [20]:
documents = df['tweet_lemmatized'].apply(' '.join,1).values
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df = 0.9, max_features = 1000, stop_words='english', lowercase=False)

# Создаем the Bag-of-Words модель
bag_of_words = count_vectorizer.fit_transform(documents)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words.toarray(), columns = feature_names)

able  absolutely  accept  account  act  ...  youth  youtube  yr  yrs  yummy
0         0           0       0        0    0  ...      0        0   0    0      0
1         0           0       0        0    0  ...      0        0   0    0      0
2         0           0       0        0    0  ...      0        0   0    0      0
3         0           0       0        0    0  ...      0        0   0    0      0
4         0           0       0        0    0  ...      0        0   0    0      0
...     ...         ...     ...      ...  ...  ...    ...      ...  ..  ...    ...
49154     0           0       0        0    0  ...      0        0   0    0      0
49155     0           0       0        0    0  ...      0        0   0    0      0
49156     0           0       0        0    0  ...      0        0   0    0      0
49157     0           0       0        0    0  ...      0        0   0    0      0
49158     0           0       0        0    0  ...      0        0   0    0      0

[49159 rows x 1000 columns]

In [21]:
documents = df['tweet_stemmed'].apply(' '.join,1).values
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df = 0.9, max_features = 1000, stop_words='english', lowercase=False)

# Создаем the Bag-of-Words модель
bag_of_words = count_vectorizer.fit_transform(documents)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words.toarray(), columns = feature_names)

abl  absolut  accept  account  act  ...  york  young  youtub  yr  yummi
0        0        0       0        0    0  ...     0      0       0   0      0
1        0        0       0        0    0  ...     0      0       0   0      0
2        0        0       0        0    0  ...     0      0       0   0      0
3        0        0       0        0    0  ...     0      0       0   0      0
4        0        0       0        0    0  ...     0      0       0   0      0
...    ...      ...     ...      ...  ...  ...   ...    ...     ...  ..    ...
49154    0        0       0        0    0  ...     0      0       0   0      0
49155    0        0       0        0    0  ...     0      0       0   0      0
49156    0        0       0        0    0  ...     0      0       0   0      0
49157    0        0       0        0    0  ...     0      0       0   0      0
49158    0        0       0        0    0  ...     0      0       0   0      0

[49159 rows x 1000 columns]

2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно. Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df. Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000. Исключим стоп-слова с помощью stop_words='english'. Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

document = df['tweet_stemmed'].apply(' '.join,1).values
tfidf_vectorizer = TfidfVectorizer(max_df=0.9,max_features=1000,stop_words='english')
values = tfidf_vectorizer.fit_transform(document)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

abl  absolut  accept  account  act  ...  york  young  youtub   yr  yummi
0      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
1      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
2      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
3      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
4      0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
...    ...      ...     ...      ...  ...  ...   ...    ...     ...  ...    ...
49154  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49155  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49156  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49157  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0
49158  0.0      0.0     0.0      0.0  0.0  ...   0.0    0.0     0.0  0.0    0.0

[49159 rows x 1000 columns]

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

document = df['tweet_lemmatized'].apply(' '.join,1).values
tfidf_vectorizer = TfidfVectorizer(max_df=0.9,max_features=1000,stop_words='english')
values = tfidf_vectorizer.fit_transform(document)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

able  absolutely  accept  account  act  ...  youth  youtube   yr  yrs  yummy
0       0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
1       0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
2       0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
3       0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
4       0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
...     ...         ...     ...      ...  ...  ...    ...      ...  ...  ...    ...
49154   0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
49155   0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
49156   0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
49157   0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0
49158   0.0         0.0     0.0      0.0  0.0  ...    0.0      0.0  0.0  0.0    0.0

[49159 rows x 1000 columns]

3. Создайте мешок слов с помощью sklearn.feature_extraction.text.HashingVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
- Ограничим количество фичей, с помощью n_features = 1000.(можно изменить)

- Исключим стоп-слова с помощью stop_words='english'.


In [24]:
from sklearn.feature_extraction.text import HashingVectorizer

document = df['tweet_lemmatized'].apply(' '.join,1).values
vectorizer = HashingVectorizer(n_features=1000, stop_words='english')
values = vectorizer.fit_transform(document)
print(values.shape)
print(values.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
from sklearn.feature_extraction.text import HashingVectorizer

document = df['tweet_stemmed'].apply(' '.join,1).values
vectorizer = HashingVectorizer(n_features=1000, stop_words='english')
values = vectorizer.fit_transform(document)
print(values.shape)
print(values.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


4. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [27]:
# Загружаем данные
data = open('/content/drive/MyDrive/Geekbrainst/corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [28]:
from sklearn import model_selection, preprocessing, linear_model
from sklearn.metrics import accuracy_score
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)


count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(trainDF['text'])

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
predictions

array([0, 1, 0, ..., 0, 0, 0])

In [30]:
def investigation_scor_vectorasers(max_features = 1000, max_df=0.9):
    count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df = max_df, max_features = max_features, stop_words='english', lowercase=False)
    tfidf_vectorizer = TfidfVectorizer(max_df=max_df,max_features=max_features,stop_words='english')
    hashing_vectorizer = HashingVectorizer(n_features=max_features, stop_words='english')

    vectorizers = [count_vectorizer, tfidf_vectorizer, hashing_vectorizer]
    scor_vs_vectorasers = []

    for v in vectorizers:
        v.fit(trainDF['text'])
        xtrain_count =  v.transform(train_x)
        xvalid_count =  v.transform(valid_x)

        classifier = linear_model.LogisticRegression()
        classifier.fit(xtrain_count, train_y)
        predictions = classifier.predict(xvalid_count)
        scor_vs_vectorasers.append([v, accuracy_score(valid_y, predictions)])
    return pd.DataFrame(scor_vs_vectorasers, columns = ['Vectoraser', 'Score'])

In [31]:
investigation_scor_vectorasers(max_features = 5000, max_df=0.9)

Vectoraser   Score
0  CountVectorizer(analyzer='word', binary=False,...  0.8424
1  TfidfVectorizer(analyzer='word', binary=False,...  0.8604
2  HashingVectorizer(alternate_sign=True, analyze...  0.8344

In [32]:
investigation_scor_vectorasers(max_features = 1000, max_df=0.6)

Vectoraser   Score
0  CountVectorizer(analyzer='word', binary=False,...  0.8216
1  TfidfVectorizer(analyzer='word', binary=False,...  0.8428
2  HashingVectorizer(alternate_sign=True, analyze...  0.7680

In [33]:
investigation_scor_vectorasers(max_features = 1000, max_df=1)

Vectoraser   Score
0  CountVectorizer(analyzer='word', binary=False,...  0.5056
1  TfidfVectorizer(analyzer='word', binary=False,...  0.5056
2  HashingVectorizer(alternate_sign=True, analyze...  0.7680